[tool.black]
line-length = 79

[tool.isort]
line_length = 79
import_heading_future = "Future library"
import_heading_stdlib = "Standard library"
import_heading_thirdparty = "Third-party"
import_heading_firstparty = "First-party"
import_heading_localfolder = "Relative"

[tool.ruff]
line-length = 79
select = [
    # flake8-builtins
    "A",
    # flake8-annotations
    "ANN",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # mccabe
    "C90",
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-pytest-style
    "PT",
    # flake8-return
    "RET",
    # flake8-bandit
    "S",
    # pyupgrade
    "UP",
    # pycodestyle
    "W"
]

ignore = [
     # Missing type annotation for `self` in method
     "ANN101",
     # Missing docstring in magic method
     "D105",
]

[tool.ruff.per-file-ignores]
"test*.py" = [
    # Use of `assert` detected
    "S101",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
